#pragma once
#include <glew.h>
#include <glfw3.h>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>
#include <map>
#include <iostream>
#include <fstream>
#include <string>
#include <sstream>
#include <vector>
#include "font.h"
#include "Graphics/CAP_graphics.h"
